### ISSUE TITLE
CentOS 7 black border in nautilus

### ISSUE THREAD

**Issue by swarnendubiswas** [LinxGem33/OSX-Arc-White#1]
Thanks for sharing the code, this should draw contributions! Here is a bug on CentOS 7:

![screenshot from 2017-01-11 17-05-01](https://cloud.githubusercontent.com/assets/7343807/21870105/70d5b8ac-d820-11e6-9969-20cc4d279449.png)

**Comment by LinxGem33** [comment]
Hi appreciate the feed back!

ill open a virtual machine and see if I can replicate the issue.

regards

**Comment by LinxGem33** [comment]
also what’s your OS, shell version, desktop etc

**Comment by swarnendubiswas** [comment]
OS is CentOS 7, and Gnome stack is at 3.14. My previous post has the details. :)

Let me know if you need more information.

**Comment by LinxGem33** [comment]
@swarnendubiswas 

please could you test the latest release and see if the issue has been resolved and report back your findings.

kind regards

**Comment by swarnendubiswas** [comment]
Unfortunately, no.

![screenshot from 2017-03-06 10-45-20](https://cloud.githubusercontent.com/assets/7343807/23619761/4356134a-025a-11e7-8155-041e97302ee1.png)

**Comment by LinxGem33** [comment]
thanks for letting me know.
kind regards

**Comment by LinxGem33** [comment]
@swarnendubiswas 
hi i haven't forgotten about your issue it seems to be my nemesis the first issue i got and the only issue i have not solved yet :) 

could you test the Arc theme ( from horst1080) and tell me if that theme has the same issue, I'm now determined to fix this issue.

kind regards

**Comment by swarnendubiswas** [comment]
No problem. I am traveling for the next two weeks, so it would be some time before I can respond.

IIRC, Arc seems to work properly with 3.14, but I will confirm.

**Comment by swarnendubiswas** [comment]
Arc works fine with 3.14.1.
![screenshot from 2017-05-18 13-30-26](https://cloud.githubusercontent.com/assets/7343807/26217896/b910fdcc-3bce-11e7-8717-5da14bd141a6.png)

The problem only seems to exist with OSX-Arc-White. In fact, the Cinnamon settings window also looks out of place as you can see.

![screenshot from 2017-05-18 13-33-04](https://cloud.githubusercontent.com/assets/7343807/26217933/d46080ac-3bce-11e7-82c1-2598483f89ef.png)

**Comment by LinxGem33** [comment]
@swarnendubiswas  

appreciate you making the time to reply back, leave it with me and ill hopefully have the fix for one of the point releases, just to make you aware support for 3.14 & 3.16 will be dropped when the 18.04LTS is released.

kind regards

**Comment by LinxGem33** [comment]
@swarnendubiswas
## 
hey could you please manually install from the main branch and test to see if the issue is now resolved and let me know.
##
kind regards

**Comment by swarnendubiswas** [comment]
Sorry, it still does not work.
