### ISSUE TITLE
Unity window decoeation - missing edges

### ISSUE THREAD

**Issue by vikz95** [LinxGem33/OSX-Arc-White#10]
I instaled the theme on Ubuntu 16:10 but I have an issue that is fixed in the official arc theme and is present in this one. The issue is this: https://github.com/horst3180/arc-theme/issues/566
And this is the article that I found and saw that the issue is now fixed: http://www.omgubuntu.co.uk/2016/06/install-latest-arc-gtk-theme-ubuntu-16-04

I hope that this will help in improving the theme.

ps: In Unity tweak tool only the white variant is present, how can I select the darker and dark versions? Maybe trying with gnome tweak tool?

**Comment by LinxGem33** [comment]
@vikz95 

appreciate the feed back, ill look into the issue and hopefully apply the fix to the next release also could you post a couple of screen shots to allow me to better pin point your issue.

in regards to your issue with selecting the theme in unity tweak tool i have a few questions 

 1. did you download the theme from github or gnome-look.org?
 2. did you download just OSX-Arc-White or all three variants separately?
 3. where did you save the themes too?
 
this should help assist me in resolving your issue. 

kind regards

**Comment by vikz95** [comment]
As you can see here (http://www.omgubuntu.co.uk/wp-content/uploads/2016/06/Screen-Shot-2016-06-05-at-18.27.27.png) the window top border is inconsistent.

But without changing nothing now I don't have anymore the issue. It's really a strange behaviour...

I only moved menus (File, View, Edit...) from global position (in the top panel) to window specific position (near the close, minimize and maximise buttons), but I don't think this was the issue. Because if I revert the process the issue is not showing.

I downloaded the theme from github, but only now I realized that the darker and dark version are another repositories. So my mistake.
I saved the themes in /usr/share/themes and if I download the other two variants will be able to install them.

Regarding the border issue I really dont know how to help because I don't know what changed and why I don't have it anymore.

Greetings.

**Comment by LinxGem33** [comment]
@vikz95 

thanks for letting me know ill keep the issue open for a little while just in case any other users has the same issue and its not a isolated incident. 

kind regards
