### ISSUE TITLE
How do i remove the top panel Shadow?

### ISSUE THREAD

**Issue by niyasns** [LinxGem33/OSX-Arc-White#13]
How to remove top panel Shadow?

**Comment by LinxGem33** [comment]
@niyasns 

If you want to change the panel shadow property it has to be done by editing the gnome shell css although i don’t recommend editing the css unless you know what you are doing the code can be found in gnome-shell/gnome-shell.css and by deleting the line box-shadow.
```
background-gradient-direction:none;
     background-color: rgba(255,255,255,0.75);
 /*  background-color: rgba(46,51,56,0.9);
 border:1px solid rgba(200,200,200,.5);*/
 box-shadow: 0px 3px 3px 1px rgba(0,0,0,0.5);
```
as mentioned above edit at your own risk i take no responsibility for system instability as every set-up is different and configured in many ways which could cause an issue.

kind regards
