### ISSUE TITLE
DEB and RPM releases

### ISSUE THREAD

**Issue by Elbullazul** [LinxGem33/OSX-Arc-White#14]
hi,

I have made a couple of Debs in the past if you want help. But first question I have is: you want to make it for release in a PPA or just the Deb file?

**Comment by LinxGem33** [comment]
hey Elbullazul 

i would prefer packaging for a PPA but for now its just for easier installation for users i would greatly appreciate it if you could show me some time ( ie screen recording of what you do) if you have the time or patience for that sort of stuff ..ha but thank you in advance if you could package the themes for me, i would be extremely grateful. 

kind regards

**Comment by LinxGem33** [comment]
@Elbullazul 

thank you so much i really apprecite that i will learn how to package eventually ..ha

if you could package (OSX-Arc White,Darker,Shadow) and make sure they are are signed and tell me the checksum i would greatly appreciate that.

again thank you.

kinds regards

**Comment by Elbullazul** [comment]
here is the first successful build (unsigned): https://drive.google.com/open?id=0B5TxTJQ38Rx8MFF1R0NkbWJRbWc

I'm having issues with my GPG key but it shouldn't be too long before I fix that bug

**Comment by LinxGem33** [comment]
@Elbullazul 

brilliant job mate, I will add you to the list of contributors on the authors file, would it be ok for me to quote you as being the maintainer of the deb packages?

also i have unpacked the package (not installed) and everything looks ok , i only have 2 issues 

1. the description  should say **osx-arc** themes are ......
2. signing the package 

other than that it can be fixed for the next release, but tremendous job Elbullazul thank you so much

checksums are:
MD5: dcfbe4db9800b4305d3089bd2d2ab937
SHA1: d4907b01ab9d48fff67a54404e80d7c7780e2d8d
SHA256: 350a20315eb3a403abbf4c7564f6064d53dae9ed45e48fbcf11ed2ecd04d7a2f

**Comment by Elbullazul** [comment]
@LinxGem33 sums match perfectly. Shure, no problem being the maintainer.

fixed the description, and also I'm trying to get debuid to sign the package, maybe a reboot will help? posting news in short

**Comment by LinxGem33** [comment]
@Elbullazul 

let me know when you've finished and ill check the package then upload.

**Comment by LinxGem33** [comment]
@Elbullazul 

good news Ive managed to figure out how to create deb packages just successfully built my packages
could you test them ive uploaded them to osx-arc releases page

**Comment by Elbullazul** [comment]
@LinxGem33 great! I was just coming to say I finally got the package signed, a weird bug with GPG and GPG2...

https://drive.google.com/open?id=0B5TxTJQ38Rx8UGZSMUdoNXphQ1k

**Comment by LinxGem33** [comment]
@Elbullazul 
really appreciate the time and effort you gave thank you, its weired i looked at your package and finally realised how to build them (i tried a few times before) so you helped me indirectly ..ha anyway don't hesitate to give me a shout if you need a hand with your projects.

kind regards
