### ISSUE TITLE
Panel color in Cinnamon: feature or bug ?

### ISSUE THREAD

**Issue by fbob** [LinxGem33/OSX-Arc-White#16]
I don't know if it's a feature or a bug but for me the cinnamon panel color does not match the one shown in your screenshot for the gnome panel ... sorry for the disturbance if it's a feature :)

Anyway OSX-ARC is the most beautiful theme I ever used.
Excellent work !
Thanks :)

**Comment by LinxGem33** [comment]
@fbob 
appreciate the feed back, your absolutely right, this is indeed a feature of cinnamon not a bug relating to the theme and also xfce has the same issue, the panel is hard coded to be dark not light, I’m currently looking at ways to override this feature in a future release.

kind regards
