### ISSUE TITLE
Align window title to the left

### ISSUE THREAD

**Issue by marioaria** [LinxGem33/OSX-Arc-White#17]
Thanks for this sweet theme. Is it somehow possible to align window title to the left?

**Comment by Elbullazul** [comment]
gsettings set org.gnome.desktop.wm.preferences button-layout close,minimize,maximize:

**Comment by marioaria** [comment]
@Elbullazul This moves buttons to the left.

**Comment by LinxGem33** [comment]
@marioaria 

hi appreciate the feed back, could i get some more information about what OS version desktop environment etc your using so i can further investigate your issue and possibly a screen shot illustrating your issue.

kind regards

**Comment by marioaria** [comment]
Not sure if it is really an issue, but for some reason it really bothers when they are in the middle :smile: 

![screenshot at 2017-04-14 00-28-49](https://cloud.githubusercontent.com/assets/27446161/25025219/05d3b1ee-20aa-11e7-8e7b-97430092f32c.png)

**Comment by Elbullazul** [comment]
@marioaria is that MATE?

**Comment by LinxGem33** [comment]
@marioaria 

After further investigation you could use this possible work around, although i do not advise changing the theme code unless you know what your doing as this could introduce system instability. anyway I think MATE uses either `metacity-theme-1.xml` or `metacity-theme-2.xml,` so you'll have to edit one of those.

You can move the title to the left by changing the x value in this [line](https://github.com/horst3180/arc-theme/blob/master/common/metacity-1/metacity-theme-2.xml#L98) and this [line](https://github.com/horst3180/arc-theme/blob/master/common/metacity-1/metacity-theme-2.xml#L104) to 0.

kind regards

**Comment by marioaria** [comment]
That did it. Thank you!
