### ISSUE TITLE
How Do I Change Transparency for Window Titlebar?

### ISSUE THREAD

**Issue by evansan** [LinxGem33/OSX-Arc-White#18]

**Comment by LinxGem33** [comment]
@evansan 
I’m closing this as there is no information and its not an actual issue or bug rather a information request.

kind regards

**Comment by evansan** [comment]
I am not familiar with functions in Github, can you provide me the information to adjust transparency?

**Comment by evansan** [comment]
@LinxGem33 
I am not familiar with functions in Github, can you provide me the information to adjust transparency?

**Comment by LinxGem33** [comment]
@evansan 
like i said you have not provided any information about your system setup etc and also changing transparency is not a simple task it involves editing more than one file and i wouldn’t advise it unless you know what you are doing.

kind regards
