### ISSUE TITLE
Font/icon spacing in Overview

### ISSUE THREAD

**Issue by treewick** [LinxGem33/OSX-Arc-White#2]
I'm currently running Antergos with Gnome Shell 3.22.2. I'm loving your theme, and it's for the most part bug-free, but one nagging issue is in Overview. With the Applications brought up, there is overlap of the icons onto the text labels. I'm attaching a screenshot showing the issue. I've tried both Paper and Super Flat Remix icons, and changing the Font for the interface to Liberation Sans. None of these configurations addressed the issue. Thanks!

![screenshot from 2017-01-13 00-06-29](https://cloud.githubusercontent.com/assets/25096023/21920124/b634136c-d924-11e6-8dd4-725c790dccb2.png)

**Comment by LinxGem33** [comment]
Hi appreciate the feed back!

yeah I can see how that would drive you crazy, ill add it to the list for the next release but if I manage to replicate and find the issue before the release ill push the fix to the repo.

I usually try release updates every month so a fix hopefully shouldn’t be to long.

regards

**Comment by denniseffing** [comment]
I am also running Antergos with Gnome 3.22.2 and I can not replicate this bug.
 
![bildschirmfoto von 2017-01-21 16-09-13](https://cloud.githubusercontent.com/assets/5879568/22174974/c31631a0-dfeb-11e6-99c8-0b6cd4e0fb72.png)
