### ISSUE TITLE
Unity toolbar overflow issue

### ISSUE THREAD

**Issue by imanhodjaev** [LinxGem33/OSX-Arc-White#21]
Hi @LinxGem33 , 

I have found a tiny issue with Unity toolbar which is rendered with 1px overflow from both sides.

![selection_025](https://cloud.githubusercontent.com/assets/354868/25341739/25840788-290a-11e7-876f-4e4fe5d0ba87.png)

I will try to make a pull-request.

Thanks.

**Comment by LinxGem33** [comment]
@imanhodjaev 
thanks you.
