### ISSUE TITLE
Weird font colorization of notifications in Gnome 3.24

### ISSUE THREAD

**Issue by denniseffing** [LinxGem33/OSX-Arc-White#22]
I know that the theme doesn't support Gnome 3.24 officially but I updated to Gnome 3.24 a few days ago anyways and since then my notifications look like this:
![instantscreen_2017-04-27_14-02-48](https://cloud.githubusercontent.com/assets/5879568/25483319/92415234-2b55-11e7-8cf6-2146108ce710.png)

As you can see in the screenshot, it looks like there is a semi-transparent grey overlay over the whole notification area. 
I updated the theme in `~/.themes` by pulling the latest commits but that didn't fix the issue.

Any thoughts?

**Comment by LinxGem33** [comment]
@denniseffing 

Hi appreciate the feed back, you are absolutely right about the notification banner, there is also an issue with the calendar weather notification and css colour styling, as your aware there has been a few  new shell updates for gnome 3.24 hopefully these minor issues should be resolved for the next point release.

**Note**: if you want to see what I’m currently working on in future or current releases and my progress you can refer to my work in progress chart [here](https://github.com/LinxGem33/OSX-Arc-White#work-in-progress)it should let you know what current issues I’ve found and working to resolve as always i really appreciate your feed back in helping find these issues.

kind regards

**Comment by LinxGem33** [comment]
going to close this issue as the fix should be in the next point release.
