### ISSUE TITLE
OpenBox Port

### ISSUE THREAD

**Issue by eutampieri** [LinxGem33/OSX-Arc-White#23]
Could you please port it to OpenBox?

**Comment by LinxGem33** [comment]
@eutampieri 

appreciate the feed back its defiantly a good idea, at the moment it would be a bit hard to take on a new project as I’m currently running multiple projects and contributing also so its more a time limitation than anything else but i will keep it in mind for maybe a future project.

kind regards

**Comment by eutampieri** [comment]
Ok, thanks

Eugenio Tampieri



> Il giorno 23 mag 2017, alle ore 23:00, Andy C <notifications@github.com> ha scritto:
> 
> appreciate the feed back its defiantly a good idea, at the moment it would be a bit hard to take on a new project as I’m currently running multiple projects and contributing also so its more a time limitation than anything else but i will keep it in mind for maybe a future project.
>
