### ISSUE TITLE
Icons color in Elementary OS Loki

### ISSUE THREAD

**Issue by flourishdna** [LinxGem33/OSX-Arc-White#25]
The nautilus sidebar icons color in Elementary OS Loki is dark as background and are not visible.

![image](https://cloud.githubusercontent.com/assets/8165585/26634665/fed5f338-4634-11e7-8b4e-097ea7d8c15a.png)

**Comment by Elbullazul** [comment]
@flourishdna are you using the latest la capitaine theme?

**Comment by LinxGem33** [comment]
@flourishdna 

please test other icon themes as the file manager side panel inherits symbolic icons so its nothing to do with the actual theme rather the icon theme you use and if that’s set up correctly try test other icon themes and maybe a older version of the icon theme in your screen shot.

kind regards
