### ISSUE TITLE
wrong permissions on files?

### ISSUE THREAD

**Issue by fossfreedom** [LinxGem33/OSX-Arc-White#26]
I was looking over the repo when I noticed that most files have executable permissions "-rwxr-xr-x" for example - all the png files

suggest set the vast majority of files to 0644.

**Comment by LinxGem33** [comment]
@fossfreedom 

really appreciate you bringing that to my attention, ill work on changing the permissions asap, if you find anything else I’ve overlooked please don’t hesitate to let me know.

kind regards
