### ISSUE TITLE
Window control not visible on some program

### ISSUE THREAD

**Issue by hozzaq** [LinxGem33/OSX-Arc-White#27]
window control is clickable but not visible on some program like dconf-editor, sublime text 3 and rhythmbox
![screenshot from 2017-06-21 00-09-29](https://user-images.githubusercontent.com/7197485/27346067-22877c3e-5616-11e7-8a25-784a7ad51998.png)
![screenshot from 2017-06-21 00-09-18](https://user-images.githubusercontent.com/7197485/27346068-228c2cc0-5616-11e7-8124-200bc595c578.png)

**Comment by LinxGem33** [comment]
@hozzaq 

appreciate the feed back, as you haven’t provided me any information about your set-up etc i cant pin point your issue, please refer to this issue #5 as it sounds familiar.

kind regards

**Comment by hozzaq** [comment]
@LinxGem33 oh wow that is exactly the same, i actually already installed gtk2-engines-pixbuf when i want to try another theme but i haven't reboot the system so it didn't fixed the problem, thanks it fixed now.
