### ISSUE TITLE
Project claims Budgie compatibility

### ISSUE THREAD

**Issue by ikeydoherty** [LinxGem33/OSX-Arc-White#28]
Hi,

I notice this theme advertises Budgie compatibility, however all evidence indicates it completely _lacks_ any Budgie support. Could you please clarify on this? It's a bit misleading to potential users who then think Budgie is "broken" because the theme doesn't contain Budgie support.

**Comment by LinxGem33** [comment]
@ikeydoherty 
##
appreciate the feed back, I’m currently working on 7 active projects at the moment and my current work flow for this quarter is - Arc menu feature development & budgie integration, i appreciate it can be frustrating but as I’m the sole developer of the OSX Arc collection project i can understand development can sometimes seem rather slow, a lot of issues arose when budgie migrated to become an official arm of Ubuntu also since i started this project i have not received a single pull request that i could merge with the main branches or help in developing this project further keeping in mind i have other time commitments and that i do this to help the community in my spare time, any help of any kind would go along way even pointing out what the actual issues may be, even this would help me in correcting them, "so in closing" Id like to hear your thoughts?
##
kind regards

**Comment by ikeydoherty** [comment]
> a lot of issues arose when budgie migrated to become an official arm of Ubuntu

This is incorrect. Budgie is my project of which I am the founder and author, and started underneath Solus. There is a Ubuntu edition using Budgie as it's desktop, but Budgie upstream (i.e. myself and my team) are not part of that, we develop Solus.

As for the "fix" - the one with least work is simple, just remove the README line that states Budgie is supported (it's not). As for future resources when you feel you wanna add (or not, that's also fine) support, I strongly recommend checking out the SASS files in the Budgie Desktop repo (src/theme)

**Comment by LinxGem33** [comment]
@ikeydoherty 
##
WOW i was really polite to you then and your reply seemed very hostile and yes i was referring to the Ubuntu desktop version.
##
but any way i will remove budgie support from the README and stop all work on budgie support and state that in any place where I’ve uploaded OSX Arc collection sorry for any inconvenience this may have caused you and i wish you well in your endeavours.
##
kind regards

**Comment by ikeydoherty** [comment]
What? How was that hostile? I gave you the facts, a solution, and a pointer where to look at in the future. I have no inconvenience - it's _you_ I'm trying to help.

**Comment by LinxGem33** [comment]
appreciate your suggestions and i have respect for your work that you’ve done in the open source community and i don’t really want to say any more on the matter as it seems that we maybe getting our wires crossed.

kind regards

**Comment by ikeydoherty** [comment]
Hold on a minute here, lad:

>  Budgie support has now been dropped due to the founder and lead developer kindly pointing out that the theme doesn’t support the budgie desktop correctly sorry for any inconvenience to any users, you can see the full issue [here](https://github.com/LinxGem33/OSX-Arc-White/issues/28)

https://github.com/LinxGem33/OSX-Arc-White/commit/ccce3d34f97c7c9136ce43077e60fa48f6be41fa

You haven't dropped any support, you didn't have it in the first place.  And now you're blaming me, publicly, to your users, for dropping the thing that didn't exist to start with .. And that I'm now causing *them* inconvenience.

Jesus Christ, man. I only asked you to clarify your position, and pointed you to resources so that you could improve it. **That** is what I get for engaging with you, is it? Duly fucking noted. 

On account of I'm not a small minded person, once you've decided where you actually stand on things without jumping off the rails (three times now: whining at me for not sending you pull requests because of your 7 projects, second for accusing me of hostility when providing you with clarification and resources, and third by trying to name and shame me in a commit to a public README) - and you actually need some resources and information, I'll still be over in the Budgie Desktop repo. Hopefully by that time you will have learned to engage better.

For now I'm putting this to bed, because frankly I'm in a state of disbelief.

**Comment by ikeydoherty** [comment]
@LinxGem33 _if_ I am held in any regard at all (I have no love for "rock stars") - then it is because I am honest, direct, and deliver on what I say I'm going to do. I am not known for beating around the bush and I'll not waste anyone's time, my own included. I'm also certainly not known for conforming with a PC image that isn't me.

That I've engaged with you in the first place and not beaten around the bush should be demonstration enough of respect. What you choose to do with that, and the facts presented to you, is entirely your decision. It's no skin off my nose, as they say.

**Comment by LinxGem33** [comment]
@ikeydoherty 
##
and here is the misunderstanding I was meaning Ubuntu budgie and you was meaning Solus budgie the mistake was me saying just Budgie in the description.

##
![budgie](https://user-images.githubusercontent.com/19158615/27552404-98f2afe8-5aa7-11e7-969a-f695c3717265.png)
##
![b2](https://user-images.githubusercontent.com/19158615/27552418-a40b6370-5aa7-11e7-9c04-d891e10c7cae.png)
##
kind regards

**Comment by Elbullazul** [comment]
@LinxGem33 I don't want to throw gazoline in the fire, but this is not *full* budgie-oriented support.

What @ikeydoherty meant (correct me if I'm wrong) is something [like this](https://github.com/B00merang-Project/macOS-Sierra/blob/master/gtk-3.20/apps/budgie.css), that gives budgie widgets a specific theming. Arc will just give out the normal GTK look to them

If you want help for budgie support I'm willing to help

regards,

**Comment by LinxGem33** [comment]
@Elbullazul 
to be honest my heart is not in it now, but i appreciate you clearing that up (now i understand what he means ) and thank you for willing to help, if you want to take over this project then your more than welcome.

kind regards

**Comment by Elbullazul** [comment]
@LinxGem33 I submitted a new organisation to manage the themes, you can join and transfer ownership to keep things a little more clean

**Comment by LinxGem33** [comment]
@Elbullazul 

ill announce that your taking over the project then transfer ownership if your ok with that.

kind regards

**Comment by Elbullazul** [comment]
@LinxGem33 you'll be helping too, right?

**Comment by LinxGem33** [comment]
yes now and again but not full-time as I’m currently developing gnome shell extensions.
