### ISSUE TITLE
Dark background also in the white theme

### ISSUE THREAD

**Issue by davidefalanga** [LinxGem33/OSX-Arc-White#29]
Hello everyone, I am trying this theme on Ubuntu 16.04 and I am experiencing some problems. The issue is that the three variants of the theme have basically no difference among each other. For example, in the white version, the background of Nautilus and other applications is dark instead (see attached screenshot). I tried to install it both from the Github repo and from the .deb provided, but the result does not change. Does anybody have the same issue or knows how to solve it?

Thanks a lot!

![screenshot from 2017-07-06 18-00-33](https://user-images.githubusercontent.com/6575462/27920516-1714dcbe-6275-11e7-8f13-ee3dff43a974.png)

**Comment by Elbullazul** [comment]
@davidefalanga remove all files except gtk.css under ~/.themes/OSX-Arc-White/gtk-3.**[VERSION NUMBER HERE]**/

**Comment by giorga8** [comment]
same problem
manjaro 17.0.2

**Comment by giorga8** [comment]
@davidefalanga do you have turned on "Global Dark Theme"? if yes then turn off and everything will be perfect

**Comment by b0rski** [comment]
Exactly same problem for me on Fedora 26. Above hints do not help. The panel stays dark even with the white version installed. Keeps me from using this beautiful theme.

**Comment by LinxGem33** [comment]
@davidefalanga  
appreciate the feed back , it sounds like you need to install this please see below:
```
sudo apt-get install gtk2-engines-pixbuf 
```
let me know if this solves your issue

also just to make you aware Im currently not in active development of this theme as Im currntly developing gnome extensions, hopefully in the near future @Elbullazul  will be maintaining this theme pack.

kind regards

**Comment by LinxGem33** [comment]
@b0rski 
appreciate your feed back ive tested on fedora 26 please see below:
##

![f26](https://user-images.githubusercontent.com/19158615/28347413-ceb8395c-6c2e-11e7-9273-c719b56c6bb1.png)
##
kind regards

**Comment by LinxGem33** [comment]
closed due to lack of response.
