### ISSUE TITLE
Transparament video in Totem

### ISSUE THREAD

**Issue by blazer69064** [LinxGem33/OSX-Arc-White#30]
Hello. When I use this theme, video background in totem becomes transparent like this.
![2017-07-30 20-01-55](https://user-images.githubusercontent.com/15829319/28755362-fab2d6b6-7561-11e7-98ef-4167b715fdaf.png)
Can I repair it?
Ubuntu 16.04 LTS, theme 1.4.3, gnome 3.18.5.

**Comment by LinxGem33** [comment]
Im not sure what this issue is as i have not seen this before but make sure you have all dependencies installed such as pixbuf etc you can find others on the main page.

kind regards

**Comment by LinxGem33** [comment]
closed due to lack of response.
