### ISSUE TITLE
Nautilus sidebar background Color

### ISSUE THREAD

**Issue by flourishdna** [LinxGem33/OSX-Arc-White#31]
I want to change the Nautilus sidebar background so which css (class) file do I need to edit? I am using OSX-Arch White theme for both shell and gtk. I am customizing the theme for the personal project. Thanks..

![selection_009](https://user-images.githubusercontent.com/8165585/29006542-bb8285be-7b0f-11e7-97f5-ece7dc130b89.png)

**Comment by LinxGem33** [comment]
appreciate the feed back as this is not a theme related bug or issue i am going to close it, regarding your question its at the bottom of the gtk-3.0.css file under nautilusFilechooser.

kind regards
