### ISSUE TITLE
Drop shadow from top panel overlaying windows

### ISSUE THREAD

**Issue by ProjectMoon** [LinxGem33/OSX-Arc-White#32]
Hi,

This is a great-looking theme. I'm having one issue, which may just be my configuration instead of a bug. The top panel shadow is covering the top bar of windows, which looks a bit weird when the windows are maximized.

![overlay](https://user-images.githubusercontent.com/183856/29240622-48a8f454-7f58-11e7-85d7-3ae27ffcaec8.png)

Distro: Gentoo

**Comment by LinxGem33** [comment]
appreciate the feed back if you want you can lower the drop shadow or remove it completely to mitigate this issue you will find the code to do so in the gnome-shell.css file under panel.

kind regards
