### ISSUE TITLE
Cannot get the menu item clearly in several apps.

### ISSUE THREAD

**Issue by Triple-Z** [LinxGem33/OSX-Arc-White#34]
In haroopad, I cannot see the exact item name when I move the cursor onto it.

![screenshot from 2017-09-01 19-36-36 crop](https://user-images.githubusercontent.com/16285716/29968323-bd0f6d36-8ee0-11e7-98c4-ef45ba215a44.png)

However, the terminal is normal.

![screenshot from 2017-09-01 19-39-36 crop](https://user-images.githubusercontent.com/16285716/29968337-d0a31758-8ee0-11e7-83c3-f678b5f4475d.png)

Also, I found ibus has this problem too.

![screenshot from 2017-09-01 19-44-13](https://user-images.githubusercontent.com/16285716/29968507-9004f3d2-8ee1-11e7-9b5e-4019ab6e412f.png)

Any help will be appreciated !!!

**Comment by LinxGem33** [comment]
appreciate the feed back please see issue #5 and
