### ISSUE TITLE
Window title text is not centered

### ISSUE THREAD

**Issue by nick-s-b** [LinxGem33/OSX-Arc-White#36]
Hi all,
I absolutely love this theme and would like to switch to it from Arc-Flatabulous but window titles bother me. They're not centered. I use Cinnamon so I'm not sure if it's DE specific.
Here's an example:

![https://i.imgur.com/R4JvQDw.jpg](https://i.imgur.com/R4JvQDw.jpg)

I've been looking at gtk.css file for a while but can't find obvious place where this could be changed. 
Any ideas anyone? Thanks so much!

**Comment by LinxGem33** [comment]
appreciate the feed back this is a duplicate issue please see #11 

kind regards
