### ISSUE TITLE
Why You Are Stop "OSX-Arc-\*" Development?

### ISSUE THREAD

**Issue by devillove084** [LinxGem33/OSX-Arc-White#39]
Almost one year,i can not see any progress for your project.I like this GTK theme very much. I wish you can continue to developing all of arc`s projects.I appreciate very much.

**Comment by LinxGem33** [comment]
appreciate the feed back, im currently developing gnome extensions at the moment but i plan to make a update to the themes on the upcoming LTS release and add some refinements and update some of the css code 

kind regards
