### ISSUE TITLE
Wrong plank theme

### ISSUE THREAD

**Issue by denniseffing** [LinxGem33/OSX-Arc-White#4]
The extra folder contains the plank theme for OSX-Arc-Darker/-Shadow and not for OSX-Arc-White.

**Comment by LinxGem33** [comment]
@denniseffing 

appreciate the feed back Ive added the capeos plank theme (e.g light theme) for OSX-Arc-White it should be included as for the Ark-plank thats been added just in case the user changes the theme to the global dark settings but Ill double check to make sure.

regards

**Comment by denniseffing** [comment]
My mistake, didn't know that Capeos was a plank theme too, so I didn't even bother to look into the Capeos directory.

**Comment by LinxGem33** [comment]
appreciate you letting me know.

regards
