### ISSUE TITLE
Not an issue!

### ISSUE THREAD

**Issue by FrankRizz0** [LinxGem33/OSX-Arc-White#42]
Hello, thanks for the best theme I've seen to date.  I have a quick question, hopefully it can be answered as such.  I would love to have the white theme with green accents (highlighting, etc.).  I know this is a lot to ask, therefore I have no problem doing it myself, but unfortunately I have never created/edited a theme before.  A little guidance would be wonderful, thank you.

**Comment by LinxGem33** [comment]
there are alot of places to direct you to that needs to be changed in order to change the highlights and also it depends which desktop your using so i would suggest get familiar with the css and it would be easier to advise you.

kind regards
