### ISSUE TITLE
disable drop shadow on maximized windows

### ISSUE THREAD

**Issue by ZachariasZeiler** [LinxGem33/OSX-Arc-White#46]
Hi, 
I stumbled about your awesome work today and fell in love with it, there's just one small hiccup I dislike: Whenever I open an application in maximized window mode (and that happen's quite often) the drop shadow of the top bar still is visible, it's shading my open application and it's really distracting. 

![topbardropshadow](https://user-images.githubusercontent.com/32845029/34652751-a2614204-f3e2-11e7-8f66-4c14075e4d1d.png)
Here's a picture of how it affects firefox, as you can see the shadow overlaps the current applicaton, even if this app is focussed. 

May it be possible to remove this shadow on maximized windows or render it on a lower level than the application itself, so the shadow doesn't lap into the application window any more?

Edit: This screenshot explains the problem even better imho: 
![shadowintellij](https://user-images.githubusercontent.com/32845029/34652944-5c11df04-f3e5-11e7-86fe-77857b5f2e4d.png)

**Comment by LinxGem33** [comment]
im looking at ways to do this hopefully for a future release as its only on the white theme, darker and shadow dont have this issue.
