### ISSUE TITLE
Wallpaper

### ISSUE THREAD

**Issue by anuragsv** [LinxGem33/OSX-Arc-White#6]
Hi Andy,

I know this is not a valid issue regarding your theme, but I did not know how else to contact you. I was wondering which wallpaper you are using in this sample [screenshot](https://camo.githubusercontent.com/2f87c2d606fced54e9c6d34259137af45428d075/68747470733a2f2f636e2e706c696e672e636f6d2f696d672f622f632f312f392f3236363366653737323463646265343830383762663866666236316566333364393237302e706e67) you provided. If you could please direct me to a place where I can download that wallpaper and other similar flat, cartoony, wallpapers that go well with the Arc theme and the Arc icon theme, I would really appreciate it.

Sorry about the improper contact. Thanks in advance.

**Comment by LinxGem33** [comment]
@anuragsv 

you can find all the wallpapers and more similiar to the one in the screenshot [here](http://simpledesktops.com/)

kind regards

**Comment by anuragsv** [comment]
@LinxGem33 

Thank you for your quick response. I visited the link you provided and browsed through all 49 pages of it, but could not find the wallpaper that you have in the screenshot. Could you please direct me to it, give me its name, or let me download your copy?

**Comment by Elbullazul** [comment]
@anuragsv I think it's [this one](http://powellong.com/wallpaper/WDF_654177.html)

![arcosx](http://powellong.com/data/wallpapers/17/WDF_654177.png)

**Comment by anuragsv** [comment]
Thank you.
