### ISSUE TITLE
Unity Top Panel

### ISSUE THREAD

**Issue by anuragsv** [LinxGem33/OSX-Arc-White#7]
Hi Andy,

I appreciate your work and like your themes a lot. I tried your OSX-Arc-White theme on my Ubuntu 16.04 system. Everything is working fine, but the unity top panel is dark like in your OSX-Arc-Darker and OSX-Arc-Shadow themes and not white like in this [screenshot](https://camo.githubusercontent.com/1f6d1df9ccb354c3181b0a06bd87e9baee7e3969/68747470733a2f2f636e2e706c696e672e636f6d2f696d672f342f372f352f302f3863343363373330303530363532303837376462393366343065313666363830303565382e706e67) (I realize this may be a screenshot of Ubuntu GNOME), while all the window borders and everything else are white like they are supposed to be.

I would really appreciate it if you could please fix it.

Thanks.

**Comment by LinxGem33** [comment]
@anuragsv 

appreciate the feed back!

the feature your requesting is planned for a future release, its something i want as well :+1: 

kind regards
