### ISSUE TITLE
File Manager Navigation Pane

### ISSUE THREAD

**Issue by anuragsv** [LinxGem33/OSX-Arc-White#8]
Hi Andy,

Thanks for you work. I noticed that in all variants of your OSX-Arc theme, you made the navigation pane of the file manager dark. While this looks good on the Darker and Shadow variants of the theme, it just doesn't go well with the White variant. I would really appreciate it if you could please make the Navigation Pane white in the OSX-Arc-White theme or provide instructions on how to configure it ourselves.

Thanks.

**Comment by LinxGem33** [comment]
@anuragsv 

this is also something which is planned for a future release.

kind regards
